name: Pipeline
on:
  push:
    branches:
    - main
    - gh-actions

  pull_request:
    - main
    - gh-actions

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    # Checkout repo
      - name: Fetch code /Checkout code
        uses: actions/checkout@v4

    #install Packages
      - name: Install dependencies
        run: npm install

    #install playwright
      - name: Install playwright
        run: npx playwright install

    #pull docker image
      - name:
        run: docker pull rasilva1986/my-vue-app:v1

    #start application 
      - name: Start the application
        run: docker run -d -p 3000:3000 rasilva1986/my-vue-app:v1

    #wait until the application is up
      - name: Wait until the application is up
        run: npx wait-on http://localhost:3000

    #run tests
      - name: Run tests
        run: npm run run-tests

    #publish results
      - name: Save test results as artifacts
        uses: actions/upload-artifacts
        with:
          name: playwright-test-results
          path: ./playwright-report
          


    #Rafael video timestamp: 21:38/42:48

#docker pull rasilva1986/my-vue-app:v1
#docker run -d -p 3000:3000 rasilva1986/my-vue-app:v1