name: Pipeline
on:
  push:
    branches:
    - main
    - gh-actions

  pull_request:
    branches: 
    - main
    - gh-actions

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    # Checkout repo
      - name: Fetch code / Checkout code
        uses: actions/checkout@v4

    # Install Packages
      - name: Install dependencies
        run: npm install

    # Install Playwright
      - name: Install Playwright
        run: npx playwright install

    # Pull Docker image
      - name: Pull Docker image  
        run: docker pull rasilva1986/my-vue-app:v1

    # Start application
      - name: Start the application
        run: docker run -d -p 3000:3000 rasilva1986/my-vue-app:v1

    # Wait until the application is up
      - name: Wait until the application is up
        run: npx wait-on http://localhost:3000

    # Run tests
      - name: Run tests
        env:
          BASE_URL: ${{secrets.BASE_URL}}
          TEST_USERNAME: ${{secrets.TEST_USERNAME}}
          TEST_PASSWORD: ${{secrets.TEST_PASSWORD}}
        run: npm run run-tests

    # Publish results
      - name: Save test results as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: ./playwright-report

          


    #Rafael video timestamp: 21:38/42:48

#docker pull rasilva1986/my-vue-app:v1
#docker run -d -p 3000:3000 rasilva1986/my-vue-app:v1